CREATE TABLE IF NOT EXISTS public_inquiries (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    property_id INT(11) NULL,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    interest ENUM('buy','sell','invest','general','property') NOT NULL DEFAULT 'general',
    message TEXT NOT NULL,
    status ENUM('new','contacted','qualified','closed','spam') NOT NULL DEFAULT 'new',
    consent_at DATETIME NOT NULL,
    ip_hash CHAR(64) NOT NULL,
    source_page VARCHAR(255) NULL,
    submission_token CHAR(48) NULL,
    assigned_to INT(11) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_public_inquiries_status_created (status, created_at),
    KEY idx_public_inquiries_property (property_id),
    KEY idx_public_inquiries_ip_created (ip_hash, created_at),
    UNIQUE KEY uq_public_inquiries_submission_token (submission_token),
    CONSTRAINT fk_public_inquiry_property FOREIGN KEY (property_id) REFERENCES seller_properties(id) ON DELETE SET NULL,
    CONSTRAINT fk_public_inquiry_assignee FOREIGN KEY (assigned_to) REFERENCES admin_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
